### ISSUE TITLE
Fix Strings

### ISSUE THREAD

**Issue by danilolekovic** [danilolekovic/iode-d#5]

**Comment by Cxarli** [comment]
Do you want me to add escaping to the strings? Because as far as I can see now, `"Hello \"World\""` will give some bad errors.

If not, maybe I could add some other things, as I'm really curious about this project and would like to contribute.

**Comment by danilolekovic** [comment]
@C-Bouthoorn That sounds great. I didn't think anybody was really interested in this project :smile:

**Comment by Cxarli** [comment]
Got to learn how to use D first, but I don't mind, it looks pretty easy to me.

What exactly are your thoughts on how you want to make it? I'm not really familiar with Swift, but do you want it more C-like

``` c
int array[10];
for(int i=0, len=10; i < len; ++i) {
    int x = array[i];
    print(x);
}
```

Or more Ruby-like

``` ruby
array = []
array.each do |x|
  puts x
end
```

I'd be more than happy to help you making this :smile:

**Comment by danilolekovic** [comment]
@C-Bouthoorn Thanks! Definitely had more Ruby-like in mind :smile:

**Comment by Cxarli** [comment]
Mind sharing your iodeas?

**Comment by phase** [comment]
```
iodeas
```

**Comment by danilolekovic** [comment]
@C-Bouthoorn Don't really have many ideas as I haven't thought about this project in a long time. But there are [some goals I outlined](https://github.com/iode-lang/iode#goals) when I first started the project.
